### ISSUE TITLE
TestRunner is totally not showed off

### ISSUE THREAD

**Issue by tophyr** [abeatte/Exercises#2]
You basically halfway reinvented JUnit, document that shit publicly so ppl can see it!

**Comment by abeatte** [comment]
Well if that is the case, then I should probably just use JUnit. Maybe Ill migrate to that and keep the runner around as an exercise in and of itself.

**Comment by abeatte** [comment]
This was resolved with commit 0c61586ac5a2e37a8be227ce1981bd9c6f039a02.
